// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package postgresql

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type OrderLineItem struct {
	ID             uuid.UUID
	ItemType       int32
	Name           string
	Price          string
	ItemStatus     int32
	IsBaristaOrder bool
	OrderID        uuid.NullUUID
	Created        time.Time
	Updated        sql.NullTime
}

type OrderOrder struct {
	ID              uuid.UUID
	OrderSource     int32
	LoyaltyMemberID uuid.UUID
	OrderStatus     int32
	Updated         sql.NullTime
}
