// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/rabbitmq/amqp091-go"
	"github.com/thangchung/go-coffeeshop/cmd/barista/config"
	"github.com/thangchung/go-coffeeshop/internal/barista/eventhandlers"
	"github.com/thangchung/go-coffeeshop/pkg/postgres"
	"github.com/thangchung/go-coffeeshop/pkg/rabbitmq"
	"github.com/thangchung/go-coffeeshop/pkg/rabbitmq/consumer"
)

// Injectors from wire.go:

func InitApp(cfg *config.Config, pg *postgres.Postgres, amqpConn *amqp091.Connection, counterOrderPub rabbitmq.EventPublisher, consumer2 *consumer.Consumer) (*App, error) {
	baristaOrderedEventHandler := eventhandlers.NewBaristaOrderedEventHandler(pg, counterOrderPub)
	app := New(cfg, pg, amqpConn, counterOrderPub, consumer2, baristaOrderedEventHandler)
	return app, nil
}
